export enum ComplianceEngagementsLabels {
    SearchBar = 'Search bar',
    SearchMagnifier = 'Search magnifier',
    NeedSupportOption = 'Need Support option',
    ClientNameDropdown = 'Client Name',
    ProfileDropdown = 'Profile',
    Select = 'Select',
    Manage = 'Manage',
}

export enum ComplianceEngagementsTableHeaders {
    Client = 'Client',
    Engagement = 'Engagement',
    EngagementType = 'Engagement Type',
    Created = 'Created',
    Status = 'Status',
}

export enum ComplianceEngagementsTableCtas {
    Select = 'Select',
    Manage = 'Manage',
}

export enum ExistingEngagementLabels {
    SelectedEngagementName = 'Selected Engagement Name',
    ShortName = 'Short Name',
    SamplePeriodStartDate = 'Sample Period Start Date',
    SamplePeriodEndDate = 'Sample Period End Date',
    Quarterly = 'Quarterly',
    Monthly = 'Monthly',
    Weekly = 'Weekly',
    Calendar = 'Calendar',
    Client = 'Client',
    ClientLogo = 'Client Logo',
    EngagementContact ='Engagement Contact',
    AddCustomService = 'Add Custom Service',
    AddProject = '+ Add Project',
    Year = 'Year',
    EngagementName ='Engagement Name',
    LinkedPriorEngagement = 'Linked Prior Engagement',
    Version = 'Version',
    Executives = 'Executives',
    PracticeLeads = 'Practice Leads',
    Managers = 'Managers',
    Consultants = 'Consultants',
    Level = 'Level',
    Family = 'Family',
    Cycle = 'Cycle',
    AddLocation = 'Add a Location',
    SaveLocations = 'Save Location(s)',
    SavedLocations = 'saved location(s)',
    Category = 'Category',
    RequestType = 'Request Type',
    Description = 'Description',
    Criteria = 'Criteria',
    DueDate = 'Due Date',
    SelectLocation = 'Location',
    CreateCustomRequest = 'Create Custom Request',
    MassUpload = 'Mass Upload',
    CreateCustomRequests = 'Create Custom Requests',
    RollForwardCustomRequests = 'Roll Forward Custom Requests From Other Engagement',
    ExportCustomRequests = 'Export Custom Requests From All Projects Being Rolled Forward',
    MassUploadSplash = 'Mass Upload from Splash Page',
    AssignConsultant = 'Assign Consultant',
    ManageLocations = 'Manage Locations',
    ServiceRequestsToggleSelected = 'Toggle Selected',
    ServiceRequestsEllipsisDropdown = 'Service Requests Ellipsis Dropdown',
    AutoAssignRolled = 'Auto-Assign Rolled Forward N/As',
    AutoAssignRoll = 'Auto-Assign Roll Forward Locations',
    LocationColumnPencil = 'Locations column pencil',
    ManageDates = 'Manage Dates',
    Approve = 'Approve',
    Publish = 'Publish',
    Open = 'Open',
    ServiceHeaderIcon = 'Service',
    FamilyVersionHeaderIcon = 'Family/Version',
    FieldDateHeaderIcon = 'Field Date',
    ExecutiveHeaderIcon = 'Executive',
    PracticeLeadHeaderIcon = 'Practice Lead',
    ManagerHeaderIcon = 'Manager',
    ConsultantHeaderIcon = 'Consultant',
    StatusHeaderIcon = 'Status',
    ServiceFilter = 'Service filter',
    FamilyVersionFilter = 'Family/Version filter',
    FieldDateFilter = 'Field Date filter',
    ExecutiveFilter = 'Executive filter',
    PracticeLeadFilter = 'Practice Lead filter',
    ManagerFilter = 'Manager filter',
    ConsultantFilter = 'Consultant filter',
    StatusFilter = 'Status filter',
    
}